DELETE FROM VM1DTA.ZPHADDR WHERE COMPANY='9' AND PSTCDE='980' AND REGNID='PH-00' AND REGNCODE='NCR';
DELETE FROM VM1DTA.ZPHADDR WHERE COMPANY='9' AND PSTCDE='960' AND REGNID='PH-00' AND REGNCODE='NCR';
DELETE FROM VM1DTA.ZPHADDR WHERE COMPANY='9' AND PSTCDE='911' AND REGNID='PH-00' AND REGNCODE='NCR';
DELETE FROM VM1DTA.ZPHADDR WHERE COMPANY='9' AND PSTCDE='1705' AND REGNID='PH-00' AND REGNCODE='NCR';
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','980',N'Asian Dev’t. Bank','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','960',N'Int’l. Rice Research Inst.','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','911',N'Nat’l. Census & Stat. Off.','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','1705',N'Ninoy Aquino Int’l. Airport','NCRPAR','Paranaque','PH-00','NCR','National Capital Region','','');