---MODIFY COLUMN [DISTRCT] IN TABLE [ZPHADDR]
IF EXISTS (SELECT * FROM sys.columns WHERE name = 'DISTRCT' and object_id in (SELECT object_id FROM sys.tables WHERE name ='ZPHADDR'))
BEGIN
	ALTER TABLE [VM1DTA].[ZPHADDR] ALTER COLUMN DISTRCT nvarchar(50);
END
GO

INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','3502',N'Peñablanca','CAG','Cagayan','PH-02','II','Cagayan Valley','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','3525',N'Sto. Niño','CAG','Cagayan','PH-02','II','Cagayan Valley','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','3103',N'Peñaranda','NUE','Nueva Ecija','PH-03','III','Central Luzon','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7007',N'Imelda','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7001',N'Ipil','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7027',N'Josefina','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7005',N'Kabalasan','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7013',N'Kumalarang','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7017',N'Labangan','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7014',N'Lakewood','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7037',N'Lapuyan','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7010',N'Mabuhay','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7026',N'Mahayag','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7038',N'Malangas','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7035',N'Margo sa Tubig','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','7021',N'Midsalip','ZAS','Zamboanga del Sur','PH-09','IX','Zamboanga Peninsula','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','911',N'Nat’l. Census & Stat. Off.','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','960',N'Int’l. Rice Research Inst.','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
INSERT INTO VM1DTA.ZPHADDR (COMPANY,PSTCDE,DISTRCT,PRVNCODE,PRVNDESC,REGNID,REGNCODE,REGNDESC,USRPF,JOBN) VALUES('9','980',N'Asian Dev’t. Bank','NCRMNLBU','Manila - Big Users','PH-00','NCR','National Capital Region','','');
